### PR TITLE
Use valueset tables for allowed values

### LINKED ISSUE #26: Use of value set updates schema for each added vaccine
Should the schema be typed with value sets for changing information, ie vaccine?
According to Article 5 in the regulation 2021/0068 it should be possible to provide a vaccination certificate containing vaccine that has been  authorised by a competent authority of a Member State (MS). That will demand a new version of the schema when ONE MS authorize a new vaccine. But the other MS may only accept it in validation. But to be able to read the data all MS needs to update the validation when one MS authorize a new vaccine. Therefore its more safe to not use value sets in schema. Better to have them accessable in one place so that verifiers can use them instead. And more cost effective also.

### PR DESCRIPTION
**Pull request by jschlyter**
This PR removes the use of value sets as enums for allowed values and use them via references to the more dynamic lookup tables. 

closes #26

### CODE REVIEW

**Review by martin-lindstrom — CHANGES_REQUESTED** [review]
We need to be very explicit on which values (i.e., from which value set) that are allowed in the comments and descriptions. (And even point to an URL holding these values).

**Comment by jschlyter** [comment]
@gabywh can you provide some insight what values are allowed?

**Comment by martin-lindstrom** [comment]
Provided that the lookup tables are held up-to-date, couldn't we refer to them? And point at the specific valueSetId?

**Comment by jschlyter** [comment]
> Provided that the lookup tables are held up-to-date, couldn't we refer to them? And point at the specific valueSetId?

Yes, but we need to state that in the description.

**Comment by gabywh** [comment]
> > Provided that the lookup tables are held up-to-date, couldn't we refer to them? And point at the specific valueSetId?
> 
> Yes, but we need to state that in the description.

In parallel to the JSON schema design, lookup tables were also *generated* from the same data source, so keeping them in-sync is not such an issue. 
The schema itself only contains the key value, the table the rest of the information -> primarily as a space-saving device but it also has the nice property that we can update value sets relatively independent of the JSON schema.

valueSetId:
1. implicit in the field you have the key for
1. we could look at versioning etc but that rather complicates things -> semantic SG and I already considered this and you will see an "active/inactive" field in the lookup tables. It is almost never the case (I'm trying hard to think of _any_ example) that values are actually removed from a data set in medical, they will just be marked invalid. This means the data set grows with a little "clutter" but ensures 100% forward-compatibility.
1. as I think I mentioned elsewhere, for e.g. vaccine type I actually removed (after discussion with Semantic SG) the system and versions specifiers from the table in the schema
  1. the values of the keys are - at least for now - all unqiue, so we do not _need_ the system specifier
  1. in some cases, the version is present, in others only the system specifier, in some none! lowest common denominator is then key value - and we know we have unique values of the keys in our data set.

**Review by gabywh — COMMENTED** [review]
I get the motivation for moving to string (is what I used as a placeholder whilst waiting on Semantic SG to define the ValueSets) -> keep things as flexible as possible.
Dropping value sets is not something I would approve.
A lot of work went into getting these ValueSets right - also with the Semantic SG - far more than maybe even the rest of the JSON Schema in total. Whilst we want to be flexible, we don't need to lose all shape completely. I think we have achieved the required flexibility whilst maintaining some structure and boundaries with the proposal as-is.

**Comment by jschlyter** [comment]
I'm not suggesting we drop the value sets, they fit perfectly in the Lookup tables where they are more dynamic.

**Comment by gabywh** [comment]
> I'm not suggesting we drop the value sets, 
PR title "drop value sets"?
Plus that's what I see in the edits: type going from defined valueset data type to generic string?

> they fit perfectly in the Lookup tables where they are more dynamic.
yes - so we have a constrained range of keys which need to be in the JSON schema - as I mentioned above, this won't ever break forward-compatibilty due to the mechanism of flagging active/inactive in the lookup table

**Comment by martin-lindstrom** [comment]
@gabywh @jschlyter The name of the PR is a bit misleading. The value sets stays. We all approve, and want, this. But we can't build a schema that is so static as it is now.

So. The step forward is to use strings and for each element point at a specific value set (in its description). Or?

**Comment by jschlyter** [comment]
@martin-lindstrom Yes, the data type in the schema can be a string (not enum) and the description of each field referring to a dataset in the lookup tables.

**Comment by jschlyter** [comment]
So I proposed:

1. Add one file per valueset:
    - covid-19-diseases
    - covid-19-lab-methods
    - covid-19-lab-result
    - covid-19-lab-test-manufacturer-and-name
    - iso3166-1-2
    - sct-vaccines-covid-19
    - vaccines-covid-19-auth-holders
    - vaccines-covid-19-names
2.  Update description for strings in the schema, e.g. "disease or agent targeted, allowed values per dataset covid-19-diseases"

Result:
- Stable schema
- Implementors can download and generate UI etc based on the value set files.

**Review by martin-lindstrom — APPROVED** [review]

**Comment by jschlyter** [comment]
Adding @dirkx as reviewer.

From my point of view, this PR on our critical path so implementors can do code generation without depending on specific versions of the schema. Also given this, the current lookup tables might no longer be needed (we can add the countries as a valueset and we're good).

**Comment by gabywh** [comment]
> PR updated with my propsal.
> 
> 1. Add one file per valueset:
>    
>    * disease-agent-targeted
>    * test-manf
>    * test-result
>    * vaccine-mah-manf
>    * vaccine-medicinal-product
>    * vaccine-prophylaxis

Fine with that.

> 2. Update description for strings in the schema, e.g. "disease or agent targeted, allowed values per dataset covid-19-diseases"
> 
> Result:
> 
> * Stable schema
> * Implementors can download and generate UI etc based on the value set files.

Not sure how this is any different to what we already have now:
* Stable schema
* Implementors can download and generate UI etc based on the value set files

These points already in place.
Removing type information and replacing it by text in comments actually moves away from supporting auto-generation as you lose any type information. Also: _relying_ on people to actually read comments has a poor track record...

What is the *core issue* you have with having the types in there? You get an enum in your code? Or something else?

**Comment by jschlyter** [comment]
> What is the _core issue_ you have with having the types in there? You get an enum in your code? Or something else?

If you generate code from schemas with enums, you have to _regenerate the code_, base based on a _reissued schema_, every time a new value is allowed or disallowed. This is also the case if you don't generate code from the schemas, but only use them for input data validation.

If we do not decouple the core schema from the value sets we have to also publish a relaxed schema, which is what developers will use everywhere. If we don't, developers will create one for us for use in their own applications (that's what I would do).

So at the end of the day, I'd like a stable schema that can live for an extended time and survive new substances, test, manufactures etc. The HCERT itself is design for just this and designing the schema the same has always - at least in my book - been a design parameter.

**Comment by martin-lindstrom** [comment]
That we resolve this is really essential. Please. 

Either keep it as it is and introduce a relaxed schema or we just approve the PR.

**Comment by gabywh** [comment]
> If you generate code from schemas with enums, you have to _regenerate the code_, base based on a _reissued schema_, every time a new value is allowed or disallowed. This is also the case if you don't generate code from the schemas, but only use them for input data validation.

1. Only new values being added, allow or disallow takes place in the lookup tables, enforced by your business rules
2. If the enum is extended you need to re-generate - sure.
If the enum is extended and you wish to make use of it in your code, you will need to update your code in some way anyway - even if that means setting the value of a parameter with type string rather than enum type. Auto-generation seems like a good option here rather than manually having to keep things in sync, agreed with that.

**Comment by jschlyter** [comment]
replaced by #30

**Pull request closed without merging**
