### PR TITLE
Digital Green Certificate -> Digital Covid Certificate

### PR DESCRIPTION
**Pull request by gabywh**
Documentation:
* Digital Green Certificate -> Digital Covid Certificate (DGC -> DCC)

JSON files:
* Filenames changed: DGC -> DCC
* $refs in JSON content changed: DGC -> DCC

### CODE REVIEW

**Comment by jschlyter** [comment]
Can we please make separate branches for each new feature? Drop `next` and create a new branch with the relevant commits please.

**Comment by jschlyter** [comment]
I've created #82 with changes from @gabywh

**Comment by gabywh** [comment]
> Can we please make separate branches for each new feature? Drop `next` and create a new branch with the relevant commits please. ping @kruzikh @gabywh

I'm fine with that - was my original proposal anyway. I've only kept to next because that is what people seem to be familiar with here, even though I don't like it and see a lot of issues with working on next. I'll wipe it once these PRs are in

**Comment by kruzikh** [comment]
Gentlmen, I would need clear guidance how to do it :-)
At this moment, I am putting new things and changes into next. How we should do it in the future?

Hynek

**Comment by jschlyter** [comment]
> Gentlmen, I would need clear guidance how to do it :-) At this moment, I am putting new things and changes into next. How we should do it in the future?

I've created a separate branch for your changes, please create a PR from that and refrain from using the old `next` branch.

**Review by kruzikh — COMMENTED** [review]
Ok for me.

**Comment by gabywh** [comment]
> Ok for me.



> > Gentlmen, I would need clear guidance how to do it :-) At this moment, I am putting new things and changes into next. How we should do it in the future?
> 
> I've created a separate branch for your changes, please create a PR from that and refrain from using the old `next` branch.

basically create a branch from main for your feature, sth like:

`git checkout -b feature/hynek-new-feature`

then do your changes and push that branch  (you will probably need `git push -u origin feature/hynek-new-feature` to create/push to  a new branch server-side)

**Pull request closed without merging**
