### PR TITLE
CBOR encoding clarifications

### PR DESCRIPTION
**Pull request by jschlyter**
Update main branch with CBOR encoding clarifications, no version changes.

### CODE REVIEW

**Review by martin-lindstrom — DISMISSED** [review]
Perhaps include an example as well?

**Comment by kruzikh** [comment]
Guys I corrected the test type in json schema and added valueset for it. Please, could you check? We need to do it quickly as implementers are on a full speed!

**Comment by jschlyter** [comment]
@kruzikh looking good from my side, but this should bump the patchlevel version of the schema IMHO.

Next time, please make PR toward next for your specific change as the PRs next to main are for version management only.

**Comment by kruzikh** [comment]
Sorry, my mistake, I am still a begginer in git :-(

**Comment by gabywh** [comment]
> Sorry, my mistake, I am still a begginer in git :-(

no problem - actually even "Next" is not standard and should be deleted. There's a whole bunch of stuff around version management (as ever) including the original "gitflow" and derivatives "gitlab flow" and "github flow" and so on... Currently we're doing none of them here :(

**Review by gabywh — APPROVED** [review]
Go :)

**Comment by gabywh** [comment]
> but this should bump the patchlevel version of the schema IMHO.
@jschlyter feel free to bump, usual semver thing

**Comment by kruzikh** [comment]
Gaby, coul'd you propage correct json schema into the main ASAP?

**Comment by gabywh** [comment]
> Gaby, coul'd you propage correct json schema into the main ASAP?

Yep, just waiting on one more reviewer to give the go ahead

**Review by gabywh — APPROVED** [review]

**Review by ijansch — DISMISSED** [review]

**Review by dirkx — DISMISSED** [review]

**Review by gabywh — APPROVED** [review]

**Review by ijansch — APPROVED** [review]

**Review by dirkx — APPROVED** [review]
Looks good to me - but this is getting a bit outsize my ken / expertise !

**Comment by jschlyter** [comment]
> no problem - actually even "Next" is not standard and should be deleted. There's a whole bunch of stuff around version management (as ever) including the original "gitflow" and derivatives "gitlab flow" and "github flow" and so on... Currently we're doing none of them here :(

Actually, we are. We have `main` as our release/master branch and `next` as our develop branch. We've merged changes into next and once we're ready to release a _set_ of new features as a release, we make a PR to `main` (and require at least 2 reviewers).

**Comment by gabywh** [comment]
> > no problem - actually even "Next" is not standard and should be deleted. There's a whole bunch of stuff around version management (as ever) including the original "gitflow" and derivatives "gitlab flow" and "github flow" and so on... Currently we're doing none of them here :(
> 
> Actually, we are. We have `main` as our release/master branch and `next` as our develop branch. We've merged changes into next and once we're ready to release a _set_ of new features as a release, we make a PR to `main` (and require at least 2 reviewers).

About the only standard thing we have here is main. We're not even doing upstream first with Next and release management also missing,. but whatever, I'm not going to start arguing about sw dev process, let's leave it at that.

**Pull request merged**
