### PR TITLE
Digital Green Certificate -> Digital Covid Certificate

### PR DESCRIPTION
**Pull request by jschlyter**
Documentation:
* Digital Green Certificate -> Digital Covid Certificate (DGC -> DCC)

JSON files:
* Filenames changed: DGC -> DCC
* $refs in JSON content changed: DGC -> DCC

replaced #81

### CODE REVIEW

**Review by gabywh — APPROVED** [review]
Approved / how could I not?

**Comment by martin-lindstrom** [comment]
Well, I guess I'll have to approve it, but I hope that all is aware that changing file names will break things out there. Personally I would have just changed the text within the files, and waited until a later stage (2.0) to change the file names.

**Comment by gabywh** [comment]
> Well, I guess I'll have to approve it, but I hope that all is aware that changing file names will break things out there. Personally I would have just changed the text within the files, and waited until a later stage (2.0) to change the file names.

never a good time to make such changes, the sooner the better

**Comment by martin-lindstrom** [comment]
> > Well, I guess I'll have to approve it, but I hope that all is aware that changing file names will break things out there. Personally I would have just changed the text within the files, and waited until a later stage (2.0) to change the file names.
> 
> never a good time to make such changes, the sooner the better
> already discussed with Jakob also

Can't argue with that :-)

**Review by martin-lindstrom — APPROVED** [review]

**Pull request merged**
