### PR TITLE
Decouple value sets

### LINKED ISSUE #26: Use of value set updates schema for each added vaccine
Should the schema be typed with value sets for changing information, ie vaccine?
According to Article 5 in the regulation 2021/0068 it should be possible to provide a vaccination certificate containing vaccine that has been  authorised by a competent authority of a Member State (MS). That will demand a new version of the schema when ONE MS authorize a new vaccine. But the other MS may only accept it in validation. But to be able to read the data all MS needs to update the validation when one MS authorize a new vaccine. Therefore its more safe to not use value sets in schema. Better to have them accessable in one place so that verifiers can use them instead. And more cost effective also.

### PR DESCRIPTION
**Pull request by jschlyter**
Based on a discussion with @gabywh and @martin-lindstrom, this PR moves the value sets to separate files and refers to them indirectly. Currently, this is done using `$comment`, which might be replaced by a proprietary property combined with relaxed JSON schema validation (of the schema itself).

TODO: Replace value set URLs with "official" ones. I suggest we let the official ones emit a redirect (HTTP 302) to the versions in the github main branch until we have a better way of handling change control. Depends on #25.

closes #26 
updates #25

### CODE REVIEW

**Comment by jschlyter** [comment]
I do suggest we annotate the value set files a tad, e.g. as below. This will make consuming them easier for developers.

```
{
  "system": "https://covid-19-diagnostics.jrc.ec.europa.eu/devices",
  "version": "2021-04-22 02:23:55 CET",
  "valueSetId": "covid-19-lab-test-manufacturer-and-name",
  "values": {
    "1232": {
      "display": "Abbott Rapid Diagnostics, Panbio COVID-19 Ag Test",
      "lang": "en",
      "active": true,
    },
    …
  }
}
```

**Review by gabywh — COMMENTED** [review]
Looking good.
If you can replace $comment with something more substantial / permanent as it can be dropped at any time during processing etc (as per JSON Schema spec) then I would be fine with approving.

**Comment by jschlyter** [comment]
> Looking good.
> If you can replace $comment with something more substantial / permanent as it can be dropped at any time during processing etc (as per JSON Schema spec) then I would be fine with approving.

I'll suggest we evaluate relaxed and go with something like `valueset-uri`.

**Comment by gabywh** [comment]
> 
> I'll suggest we evaluate relaxed and go with something like `valueset-uri`.

Perfect. Can you update the code here?

**Review by gabywh — APPROVED** [review]
Looks good, thanks!

**Review by martin-lindstrom — APPROVED** [review]

**Pull request merged**
